export const blogData = [
  {
    id: 1,
    title: 'First blog post',
    description: 'This is the first blog post',
    imageUrl: 'https://example.com/images/blog1.jpg',
    thumbnailUrl: 'https://example.com/images/blog1-thumb.jpg',
    categories: ['category1', 'category2'],
    author: 'John Doe',
    createdAt: '2022-01-01T00:00:00.000Z',
    isApproved: true,
  },
  {
    id: 2,
    title: 'Second blog post',
    description: 'This is the second blog post',
    imageUrl: 'https://example.com/images/blog2.jpg',
    thumbnailUrl: 'https://example.com/images/blog2-thumb.jpg',
    categories: ['category2', 'category3'],
    author: 'Jane Doe',
    createdAt: '2022-01-02T00:00:00.000Z',
    isApproved: true,
  },
  {
    id: 3,
    title: 'Third blog post',
    description: 'This is the third blog post',
    imageUrl: 'https://example.com/images/blog3.jpg',
    thumbnailUrl: 'https://example.com/images/blog3-thumb.jpg',
    categories: ['category1', 'category3'],
    author: 'John Smith',
    createdAt: '2022-01-03T00:00:00.000Z',
    isApproved: false,
  },
];
